#!/usr/bin/env python3
"""Build script for bfe001.net — generates static HTML from Markdown content and Jinja2 templates."""

import re
import sys
from pathlib import Path

import markdown
import yaml
from jinja2 import Environment, FileSystemLoader

ROOT = Path(__file__).parent
CONTENT_DIR = ROOT / "content"
TEMPLATE_DIR = ROOT / "templates"
OUTPUT_DIR = ROOT

DEFAULT_LANG = "en"
GENERATED_COMMENT = "<!-- Generated by build.py — edit content/ and templates/ instead -->\n"


def discover_languages():
    """Find all language directories under content/."""
    return sorted(d.name for d in CONTENT_DIR.iterdir() if d.is_dir() and (d / "strings.yaml").exists())


def load_yaml(path):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_markdown_file(path):
    """Load a markdown file, return (frontmatter_dict, body_text)."""
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    if content.startswith("---"):
        _, fm, body = content.split("---", 2)
        meta = yaml.safe_load(fm) or {}
        return meta, body.strip()
    return {}, content.strip()


def render_markdown(text):
    """Convert Markdown text to HTML."""
    md = markdown.Markdown(extensions=["extra"])
    return md.convert(text)


def split_sections(body):
    """Split page body into sections by <!-- section: $ADDR "Title" --> comments."""
    pattern = r'<!--\s*section:\s*(\$\S+)\s+"([^"]+)"\s*-->'
    parts = re.split(pattern, body)

    sections = []
    # parts[0] is content before any section marker (usually empty)
    i = 1
    while i + 2 <= len(parts):
        addr = parts[i]
        title = parts[i + 1]
        content = parts[i + 2] if i + 2 < len(parts) else ""
        sections.append(
            {"addr": addr, "title": title, "content": render_markdown(content.strip())}
        )
        i += 3
    return sections


def load_timeline_entries(timeline_dir):
    """Load timeline entries from individual .md files, sorted by filename.
    Returns a list of sections, each with a 'name' and 'entries' list.
    Entries with a 'section' frontmatter field start a new section."""
    all_entries = []
    for path in sorted(timeline_dir.glob("[0-9]*.md")):
        meta, body = load_markdown_file(path)
        meta["content"] = render_markdown(body)
        all_entries.append(meta)

    # Group into sections
    sections = []
    current = {"name": None, "entries": []}
    for entry in all_entries:
        if entry.get("section"):
            if current["entries"]:
                sections.append(current)
            current = {"name": entry.pop("section"), "entries": [entry]}
        else:
            current["entries"].append(entry)
    if current["entries"]:
        sections.append(current)
    return sections


def build_page(env, template_name, context, output_path):
    """Render a template and write to output."""
    template = env.get_template(template_name)
    html = GENERATED_COMMENT + template.render(**context)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"  {output_path.relative_to(ROOT)}")


def build_amiga_subpages(env, lang, languages, common, out_dir):
    """Build Amiga sub-pages from content/{lang}/amiga/*.md."""
    amiga_dir = CONTENT_DIR / lang / "amiga"
    if not amiga_dir.exists():
        return []

    # First pass: collect metadata
    subpages = []
    for path in sorted(amiga_dir.glob("*.md")):
        meta, body = load_markdown_file(path)
        slug = path.stem
        subpages.append({
            "slug": slug,
            "addr": meta.get("addr", ""),
            "title": meta.get("title", slug),
            "order": meta.get("order", 99),
            "path": f"amiga/{slug}.html",
        })

    # Sort by order field
    subpages.sort(key=lambda p: p["order"])

    # Second pass: render all pages
    for i, page in enumerate(subpages):
        path = amiga_dir / f"{page['slug']}.md"
        meta, body = load_markdown_file(path)
        sections = split_sections(body)
        prev_page = subpages[i - 1] if i > 0 else None
        next_page = subpages[i + 1] if i < len(subpages) - 1 else None

        # Sub-pages are one directory deeper
        sub_root = "../" + common["root"]

        build_page(
            env,
            "amiga_page.html",
            {
                **common,
                **meta,
                "root": sub_root,
                "nav_root": "../",
                "sections": sections,
                "active_page": "amiga",
                "active_page_path": f"amiga/{page['slug']}",
                "amiga_subpages": subpages,
                "prev_page": prev_page,
                "next_page": next_page,
            },
            out_dir / "amiga" / f"{page['slug']}.html",
        )

    return subpages


def build_lang(env, lang, languages):
    """Build all pages for a language."""
    lang_dir = CONTENT_DIR / lang
    strings = load_yaml(lang_dir / "strings.yaml")

    if lang == DEFAULT_LANG:
        out_dir = OUTPUT_DIR
        root = ""
    else:
        out_dir = OUTPUT_DIR / lang
        root = "../"

    common = {
        "lang": lang,
        "strings": strings,
        "root": root,
        "languages": languages,
        "current_lang": lang,
        "default_lang": DEFAULT_LANG,
    }

    # --- Index page ---
    meta, body = load_markdown_file(lang_dir / "index.md")
    sections = split_sections(body)
    build_page(
        env,
        "index.html",
        {**common, **meta, "sections": sections, "active_page": "index"},
        out_dir / "index.html",
    )

    # --- Mind page ---
    meta, body = load_markdown_file(lang_dir / "mind.md")
    sections = split_sections(body)
    build_page(
        env,
        "page.html",
        {**common, **meta, "sections": sections, "active_page": "mind"},
        out_dir / "mind.html",
    )

    # --- Amiga sub-pages (build before main page to get subpage list) ---
    amiga_subpages = build_amiga_subpages(env, lang, languages, common, out_dir)

    # --- Amiga page ---
    meta, body = load_markdown_file(lang_dir / "amiga.md")
    sections = split_sections(body)
    build_page(
        env,
        "page.html",
        {**common, **meta, "sections": sections, "active_page": "amiga",
         "amiga_subpages": amiga_subpages},
        out_dir / "amiga.html",
    )

    # --- Timeline page ---
    timeline_dir = lang_dir / "timeline"
    intro_meta, intro_body = load_markdown_file(timeline_dir / "_intro.md")
    timeline_sections = load_timeline_entries(timeline_dir)
    build_page(
        env,
        "timeline.html",
        {
            **common,
            **intro_meta,
            "intro": render_markdown(intro_body),
            "timeline_sections": timeline_sections,
            "active_page": "timeline",
        },
        out_dir / "timeline.html",
    )


def main():
    env = Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)))
    languages = discover_languages()

    if not languages:
        print("No languages found in content/. Nothing to build.", file=sys.stderr)
        sys.exit(1)

    print("Building bfe001.net...")
    for lang in languages:
        print(f"\n[{lang}]")
        build_lang(env, lang, languages)

    print("\nDone.")


if __name__ == "__main__":
    main()
